### PR TITLE
pkp/pkp-lib#4946 Add publisher place setting to Citation Style Language plugin

### PR DESCRIPTION
**Pull request by asmecher**

### CODE REVIEW

**Comment by NateWr** [comment]
This looks good. Can we provide any further guidance to the user about this field? Is the publisher location meant to be an institution, a city, a country? A full address or just an arbitrary string?

**Comment by asmecher** [comment]
I originally had it as "Publisher Location (ABNT)" but backed out of that because it's actually not showing in the ABNT citation (which was [the original issue's use case](https://github.com/pkp/pkp-lib/issues/4946)) and it is in others (e.g. BibTeX). The CSL spec only describes it as ["geographic location of the publisher"](http://docs.citationstyles.org/en/stable/specification.html) so I suppose we could standardize on that same terminology -- deficient though it may be?

**Comment by NateWr** [comment]
Some of the other `*-place` specifications show a city/country. Maybe let's add a description to the field that says:

> Some citation formats request the geographic location of the publisher, such as "London, U.K.".

**Comment by asmecher** [comment]
Agreed -- done. Thanks, @NateWr, shall I go ahead and merge/forward-port?

**Comment by NateWr** [comment]
Yes! :+1:

**Pull request merged**
