### PR TITLE
Upgrade citation-style files for future releases

### PR DESCRIPTION
**Pull request by JhonathanLepidus**
Related to the issues https://github.com/pkp/pkp-lib/issues/5629 and https://github.com/pkp/pkp-lib/issues/6700

### CODE REVIEW

**Comment by JhonathanLepidus** [comment]
Some of the citation-style files were not upgraded correctly. We're going to fix them as soon as possible.

**Comment by asmecher** [comment]
@NateWr, could you take a look at this?

**Comment by JhonathanLepidus** [comment]
The citation-style files were upgraded in order to match with the corresponding files in the [v1.0.2 branch of CSL](https://github.com/citation-style-language/styles/tree/v1.0.2).

**Comment by NateWr** [comment]
Replaced by https://github.com/pkp/citationStyleLanguage/pull/93

**Pull request closed without merging**
