### PR TITLE
Update ABNT-NBR 6023 from 2002 to 2018 standard

### PR DESCRIPTION
**Pull request by diegoabadan**
Updating to the latest ABNT standard

According to a librarian specialized in this standard, https://www.zotero.org/styles/universidade-de-sao-paulo-escola-de-comunicacoes-e-artes-abnt is a more correct and current implementation. Change only in the title to make it clear that it is the updated standard and not the name of the institution that updated this template.

### CODE REVIEW

**Comment by diegoabadan** [comment]
TODO: update version.xml

**Comment by NateWr** [comment]
Hi @diegoabadan,

Thanks, for letting us know. We draw all of our styles from the official repository at https://github.com/citation-style-language/styles. It looks like the style we are using, `associacao-brasileira-de-normas-tecnicas.csl`, has been updated in May: https://github.com/citation-style-language/styles/blob/master/associacao-brasileira-de-normas-tecnicas.csl.

The style you suggested, `universidade-de-sao-paulo-escola-de-comunicacoes-e-artes-abnt.csl`, was updated last December: https://github.com/citation-style-language/styles/blob/master/universidade-de-sao-paulo-escola-de-comunicacoes-e-artes-abnt.csl

Can you ask your colleague if the updated version of `associacao-brasileira-de-normas-tecnicas.csl` is accurate? Perhaps our version is just out-dated and I'd rather update a version that we have actively in-use rather than switch to a different style, because this will force an unexpected change on all of our users.

However, if the original really isn't in wide use, then we'll need to investigate that and make the switch as appropriate.

**Comment by diegoabadan** [comment]
Hello Nate!

I checked it myself and, unfortunately, the last two commits are very small changes. It remains the 2003 standard:
https://github.com/citation-style-language/styles/blob/master/associacao-brasileira-de-normas-tecnicas.csl#L41

The one I indicated, from December is updated for 2018:
https://github.com/citation-style-language/styles/blob/master/universidade-de-sao-paulo-escola-de-comunicacoes-e-artes-abnt.csl#L17
(the important thing is the end: ABNT-NBR 6023.**2018**)

I am sure that the Brazilian public that adopts the national standard will be very happy to update to the latest version, from 2018. Many do not know the standard and end up trusting what the OJS shows them. In any case, we received some complaints about its outdating and I finally had time to deal with it.

Note: We host hundreds of Brazilian journals with OJS and therefore we have a lot of feedback from the target audience of the ABNT standard. :)

**Comment by NateWr** [comment]
Thanks @diegoabadan, that sounds convincing to me. I will just run it by some community contacts for feedback as well before merging.

**Comment by NateWr** [comment]
Thanks again @diegoabadan! I've merged that to `master` and to the `stable-3_2_1` branch. I'll note it down as a plugin we need to release with our next maintenance update. :+1:

**Comment by diegoabadan** [comment]
Thank you, Nate!

**Pull request merged**
